version: '3.8'

services:

  db:
    image: mongo:7.0.4
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}

    ports:
      - "27017:27017"
    volumes:
      - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./docker-entrypoint-initdb.d/ppna.csv:/docker-entrypoint-initdb.d/ppna.csv:ro
    networks:
      - vnet1

  mgmt-api:
    build: . 
    command: python -u app.py 
    ports: 
      - 5000:5000
    volumes:
      - .:/ppnaforecast
    networks:
      - vnet1
    depends_on:
      - db

networks:
  vnet1:
    driver: bridge