services:
  db: 
    image: mongo:7.0.4
    hostname: mongodb
    environment:
      - MONGO_INITDB_DATABASE=ppna_forecast_db
    ports:
      - 27017:27017
    volumes:
      - ./initMongo/init-mongo.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - vnet1

  api:
    build: . 
    command: python -u app.py 
    ports: 
      - 5000:5000
    volumes:
      - .:/ppnaforecast
    networks:
      - vnet1
    depends_on:
      - db

networks:
  vnet1:
    driver: bridge